# Generated by Django 5.0.3 on 2024-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_webpage_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
